P0   avatar & badge
saicharan-gouru/Spazeir-UI pull request #1
Opened 2022-01-29 16:40 UTC by saicharan-gouru

Please review my avatar and badge components. I have attached the demos below.

Avatar component

![Screenshot (175)](https://user-images.githubusercontent.com/62795476/151669210-81cae6ff-2905-45fa-aeea-5386f6fa8b26.png)

Badge component

![badge](https://user-images.githubusercontent.com/62795476/151669237-dc11d61a-a3f0-46fa-af52-8afdb07fef19.gif)

2022-01-29 16:45 UTC, Creator-singh approved these changes
looks good to go ahead🚀

2022-01-29 16:48 UTC, ranitasahaa1230 approved these changes
Looks good to me!

2022-01-29 16:55 UTC, Mohasin-Haque reviewed
Looks good.. everything is so cool.. But how about changing the classes like 
from small-avatar to avatar small.. Its in you BTW.. Great work😊

2022-01-29 17:17 UTC, maitrakhatri requested changes
in badge.css file, badge-on-text/ large-b... / button1 / badge-on-button /badge-on icon have many properties same such as position, width, font-size, padding, border-radius, color and font-weight. only the position dimensions are different. So instead of repeating the CSS, you can make a class and give all the elements same class

2022-01-29 17:50 UTC, saicharan-gouru commented
> in badge.css file, badge-on-text/ large-b... / button1 / badge-on-button /badge-on icon have many properties same such as position, width, font-size, padding, border-radius, color and font-weight. only the position dimensions are different. So instead of repeating the CSS, you can make a class and give all the elements same class

Thanks for the review. I have made the changes.

2022-01-29 17:53 UTC, saicharan-gouru commented
> Thanks for the review. I have made the changes.

Thanks for the review. I have made the changes.

2022-01-29 18:23 UTC, shilpe26 commented on badge/badge.css
> +    padding: 0.2rem 0.5rem;
consider using *px* instead of rem when value is < 1rem or 10px, as told by Vikram Sir

2022-01-30 08:32 UTC, Arpit-dotcom commented
Good one

2022-02-04 12:23 UTC, merged